### ISSUE TITLE
fatal error: 'audio_recorder/audio_recorder-Swift.h' file not found

### ISSUE THREAD

**Issue by SeniorIvan** [ZaraclaJ/audio_recorder#21]
I have build error:

`    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Debug ===
    .../.pub-cache/hosted/pub.dartlang.org/audio_recorder-0.0.6/ios/Classes/SwiftAudioRecorderPlugin.swift:88:13: warning: default will never be executed
                default:
                ^
    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Debug ===
    .../.pub-cache/hosted/pub.dartlang.org/audio_recorder-0.0.6/ios/Classes/AudioRecorderPlugin.m:2:9: fatal error: 'audio_recorder/audio_recorder-Swift.h' file not found
    #import <audio_recorder/audio_recorder-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.`

in xcode:
![2018-09-14 17 45 17](https://user-images.githubusercontent.com/11444783/45553841-fd7ecd00-b845-11e8-93b5-c0c880a2a6a0.png)

**Comment by SeniorIvan** [comment]
seem error occurred, because   use_frameworks! removed from podfile, it is required firebase plugin

**Comment by ZaraclaJ** [comment]
Can you send me a sample where i can reproduce your error ?

**Comment by SeniorIvan** [comment]
how reproduce:

1) create flutter project on Swift.
2) include firebase_messaging plugin(may be not required)
3) Remove the use_frameworks! (see iOS Integration https://pub.dartlang.org/packages/firebase_messaging )
4) build project
5) build error occurred

**Comment by ferbass** [comment]
@SeniorIvan I solved this problem only adding the `use_framework!` back

**Comment by linguitang** [comment]
@ferbass  use_framework?What's the meaning?

**Comment by ferbass** [comment]
> @ferbass use_framework?What's the meaning?

@linguitang in your Podfile please check if the `use_framework!` line is commented, if commented please remove # and try again

**Comment by SametSahin10** [comment]
I'm getting this error because I had to comment out `use_framework!` on Podfile to solve another problem. Is this the only solution?

> > @ferbass use_framework?What's the meaning?
> 
> @linguitang in your Podfile please check if the `use_framework!` line is commented, if commented please remove # and try again

**Comment by nightwolf-chen** [comment]
Changing <audio_recorder/audio_recorder-Swift.h> to "audio_recorder-Swift.h" should fix it.

**Comment by NTJ3** [comment]
@nightwolf-chen, @ferbass , @ivk1800

Header 'audio_recorder-Swift.h' not found

```
framework module audio_recorder {
  umbrella header "audio_recorder-umbrella.h"

  export *
  module * { export * }
}

module audio_recorder.Swift {
    header "audio_recorder-Swift.h"
    requires objc
}
```

added `use_framework!` in pod file is anything left to change cause still facing errors.
